site_name: 2021 RL Virtual School
site_description: 2021 Reinforcement Learning Virtual School
site_url: https://RL-VS.github.io/rlvs2021
site_dir: site
strict: false
use_directory_urls: false
edit_uri: edit/main/docs/

theme:
  name: 'cinder'
  logo: 'https://raw.githubusercontent.com/RL-VS/rlvs2021/main/docs/img/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/RL-VS/rlvs2021/main/docs/img/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: RL-VS/rlvs2021
repo_url: https://github.com/RL-VS/rlvs2021

nav:
- RLVS home: index.md
- Classes: 
    - RLVS overview: rlvs-overview.md
    - RL fundamentals: rl-fundamentals.md
    - Intro to Deep Learning: deep-learning.md
    - Human behavioral agents: human-behavioral-agents.md
    - Stochastic bandits: stochastic-bandits.md
    - Monte Carlo Tree Search: mcts.md
    - Multi-armed bandits in clinical trials: clinical.md
    - Deep Q-Networks and its variants: dqn.md
    - Regularized MDPs: regularized-mdps.md
    - Policy Gradients and Actor Critic methods: pg.md
    - Pitfalls in Policy Gradient methods: pg-pitfalls.md
    - Exploration in Deep RL: exploration.md
    - Evolutionary Reinforcement Learning: evo-rl.md
    - Micro-data Policy Search: micro-data.md
    - RL tips and tricks: tips-and-tricks.md
    - Symbolic representations and reinforcement learning: symbolic.md
    - Leveraging model-learning for extreme generalization: model-learning.md
- Speakers:
    - D. A. Berry: donald-berry.md
    - K. Chatzilygeroudis: konstantinos-chatzilygeroudis.md
    - M. Garnelo: marta-garnelo.md
    - M. Geist: matthieu-geist.md
    - L. P. Kaelbling: leslie-kaelbling.md
    - T. Lattimore: tor-lattimore.md
    - J.-B. Mouret: jean-baptiste-mouret.md
    - B. Piot: bilal-piot.md
    - M. Pirotta: matteo-pirotta.md
    - E. Rachelson: emmanuel-rachelson.md
    - A. Raffin: antonin-raffin.md
    - I. Rish: irina-rish.md
    - S. Risi: sebastian-risi.md
    - O. Sigaud: olivier-sigaud.md
    - C. Tallec: corentin-tallec.md
    - M. Wang: mengdi-wang.md
    - D. Wilson: dennis-wilson.md
- Organizers: organizers.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search

