site_name: Reinforcement Learning
site_description: Introduction to reinforcement learning class, given at ISAE-Supaero
site_url: https://supaerodatascience.github.io/reinforcement-learning/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'cinder'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/RL-VS/rlvs2021/master/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/RL-VS/rlvs2021/master/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: RL-VS/rlvs2021
repo_url: https://github.com/RL-VS/rlvs2021

nav:
- RLVS home: index.md
- Classes: 
    - RLVS overview: rlvs-overview.md
- Speakers:
    - E. Rachelson: emmanuel-rachelson.md
- Organizers: organizers.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
